jwt:
  secret: '[a-zA-Z0-9._]^+$Guidelines89797987forAlphabeticalArraNumeralsandOtherSymbo$'


server:
  port: 8081
#  error:
#    whitelabel:
#      enabled: false

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/FullStack?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC #change this to your database url
    password: Nevergiveup7
    username: root
    jpa:
    show-sql: true
    hibernate:
      ddl-auto: update #cuz  create going to drop the table and  create the table again
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false